spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/mc_cost
    username: root
    password: 1234
  thymeleaf:
    cache: true
    check-template: true
    prefix: classpath:templates/
    suffix: .html
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  mvc:
    static-path-pattern: /static/**
  devtools:
    livereload:
      enabled: true

mybatis:
  type-aliases-package: com.board.boardTest.persistence
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
  mapper-locations: classpath:/board/mapper/*.xml




