spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: 12345678
  thymeleaf:
    cache: true
    check-template: true
    prefix: classpath:templates/
    suffix: .html
  mvc:
    static-path-pattern: /static/**

mybatis:
  type-aliases-package: com.board.boardTest.persistence
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
  mapper-locations: classpath:/board/mapper/*.xml




