spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.0.200:3309/test_check
    username: root
    password: qwer1234!@
  thymeleaf:
    cache: true
    check-template: true
    prefix: classpath:templates/
    suffix: .html
  mvc:
    static-path-pattern: /static/**

mybatis:
  type-aliases-package: com.board.boardTest.persistence
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
  mapper-locations: classpath:/board/mapper/*.xml




